{ pkgs, inputs, ... }:
{
  home.packages = with pkgs; [
    (callPackage ../modules/ass.nix { })
    #inputs.nix-citizen.packages.${system}.star-citizen
    #inputs.nix-citizen.packages.${system}.star-citizen-helper
    #inputs.nix-citizen.packages.${system}.lug-helper
    #unstable.teamspeak6-client
    equibop
    signal-desktop
    r2modman
    unstable.noctalia-shell
    memtester
    edhm-ui
    ed-odyssey-materials-helper
    freecad
    min-ed-launcher
    manix
    qbittorrent
    libreoffice
    ungoogled-chromium
    heroic
    chafa
    chirp
    rofi
    xfce.thunar
    gh
    ripgrep
    lutris
    steam
    protonup-qt
    wl-clipboard
    hyfetch
    gimp
    thunderbird
    nicotine-plus
    nwg-panel
    btop
#    signal-desktop
    vlc
    kdePackages.ark
    swww
    nextcloud-client
    pavucontrol
    winetricks
    wine-staging
    wine
    grimblast
    tmux
    mgba
    prusa-slicer
    moonlight-qt
    picard
    librewolf
    kdePackages.kdenlive
    cosmic-ext-tweaks
    quick-webapps
  ];

}
