{ pkgs, inputs, ... }:
{
  home.packages = with pkgs; [
    (callPackage ../modules/ass.nix { })
    inputs.nix-citizen.packages.${system}.star-citizen
    inputs.nix-citizen.packages.${system}.lug-helper
    #unstable.teamspeak6-client
    vesktop
    vivaldi
    gpu-screen-recorder-gtk
    superfile
    discord
    obsidian
    protontricks
    firefox-bin
    nushell
    fastfetch
    wonderdraft
    signal-desktop
    unstable.noctalia-shell
    edhm-ui
    ed-odyssey-materials-helper
    min-ed-launcher
    manix
    qbittorrent
    libreoffice
    ungoogled-chromium
    heroic
    chafa
    chirp
    rofi
    xfce.thunar
    gh
    ripgrep
    lutris
    steam
    protonplus
    wl-clipboard
    gimp
    thunderbird
    nicotine-plus
    nwg-panel
    btop
    vlc
    kdePackages.ark
    swww
    nextcloud-client
    pavucontrol
    winetricks
    wine-staging
    wine
    grimblast
    mgba
    prusa-slicer
    picard
    librewolf
    kdePackages.kdenlive
    cosmic-ext-tweaks
    quick-webapps
  ];

}
